name: PHP CI Branch Master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pemeriksaan-sintaks:

    runs-on: ubuntu-latest

    steps:
    - name: Mengambil repositori
      uses: actions/checkout@v2

    - name: Menyiapkan PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extension-csv: mbstring, intl, json, libxml, xml, xdebug

    - name: Memvalidasi sintaks PHP
      run: find . -name "*.php" -exec php -l {} \;
